apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Values.global.namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: jaeger-collector.istio-system.svc.cluster.local:14250
        tls:
          insecure: true
      zipkin:
        endpoint: http://zipkin.istio-system:9411/api/v2/spans
      azuremonitor:
        instrumentation_key: "<YOUR_AZURE_MONITOR_INSTRUMENTATION_KEY>"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
