{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.name }}-sa
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svc.name }}
    azure.workload.identity/use: "true"
  {{- if $svc.workloadIdentity }}
  annotations:
    azure.workload.identity/client-id: "{{ $svc.workloadIdentity.clientId }}"
    azure.workload.identity/tenant-id: "{{ $.Values.global.tenantId }}"
  {{- end }}
{{- end }}
