{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.name }}-sa
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svc.name }}
  annotations:
    azure.workload.identity/client-id: "{{ $key }}-managed-identity-client-id"
{{- end }}
