// <auto-generated />
using System;
using HealthQCopilot.Agents.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthQCopilot.Agents.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    [Migration("20260424061229_AddWorkflowOperations")]
    partial class AddWorkflowOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.AgentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGuardApproved")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Latency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("agent_decisions", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.DemoInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageNps")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAnalysis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsAnalyzed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopStrengths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopWeaknesses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.ToTable("demo_insights", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.DemoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuideSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("demo_sessions", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.EscalationQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("escalation_queue", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.GuideConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("guide_conversations", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.GuideMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("guide_messages", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.ModelRegistryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeployedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvalNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastEvalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginManifest")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeployedAt");

                    b.HasIndex("IsActive");

                    b.ToTable("model_registry_entries", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.OverallFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturePriorities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NpsScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId")
                        .IsUnique();

                    b.ToTable("demo_overall_feedbacks", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.PromptEvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelRegistryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedCases")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PassedThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalCases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("ModelRegistryEntryId");

                    b.ToTable("prompt_evaluation_runs", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.PromptExperimentOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChallengerGuardPassed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChallengerLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChallengerOutput")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlGuardPassed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ControlLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlOutput")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperimentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("prompt_experiment_outcomes", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.ReasoningAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentDecisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardVerdict")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RagChunkIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningStepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentDecisionId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("reasoning_audit_entries", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.StepFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.ToTable("demo_step_feedbacks", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.TriageWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentReasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalNote")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedLevel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPractitionerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSlotId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncounterStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HumanReviewDueAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestExceptionCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestExceptionMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAttention")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevenueStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WaitlistQueuedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookedAt");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequiresAttention");

                    b.HasIndex("Status");

                    b.ToTable("triage_workflows", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Infrastructure.Persistence.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.GuideMessage", b =>
                {
                    b.HasOne("HealthQCopilot.Domain.Agents.GuideConversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.OverallFeedback", b =>
                {
                    b.HasOne("HealthQCopilot.Domain.Agents.DemoSession", null)
                        .WithOne("OverallFeedback")
                        .HasForeignKey("HealthQCopilot.Domain.Agents.OverallFeedback", "DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.StepFeedback", b =>
                {
                    b.HasOne("HealthQCopilot.Domain.Agents.DemoSession", null)
                        .WithMany("StepFeedbacks")
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.DemoSession", b =>
                {
                    b.Navigation("OverallFeedback");

                    b.Navigation("StepFeedbacks");
                });

            modelBuilder.Entity("HealthQCopilot.Domain.Agents.GuideConversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
