apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scheduling-service-policy
  namespace: healthq-copilot
spec:
  podSelector:
    matchLabels:
      app: scheduling-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ai-agent-service
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: fhir-service
        - podSelector:
            matchLabels:
              app: notification-service
