namespace HealthQCopilot.Infrastructure.AI;

/// <summary>
/// Tracks Azure OpenAI token consumption per agent and tenant for cost attribution.
/// Emits OpenTelemetry counters that drive Grafana cost-per-tenant dashboards
/// and Azure Cost Management tag-based billing analysis.
/// </summary>
public interface ILlmUsageTracker
{
    /// <summary>
    /// Records token usage and latency for a single LLM call.
    /// </summary>
    /// <param name="promptTokens">Input tokens sent (prompt + context + RAG chunks).</param>
    /// <param name="completionTokens">Output tokens generated by the model.</param>
    /// <param name="agentName">Logical agent name (e.g., "TriageAgent", "GuideAgent").</param>
    /// <param name="tenantId">Tenant identifier for cost allocation.</param>
    /// <param name="latencyMs">End-to-end call latency in milliseconds.</param>
    void TrackUsage(int promptTokens, int completionTokens, string agentName, string tenantId, double latencyMs);
}
