apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthq-copilot-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/imatiqul/azure-ai-cloud-healthcare.git
    targetRevision: develop
    path: infra/helm
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: healthq-copilot-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
